# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# see https://www.r-bloggers.com/travis-ci-for-r%E2%80%8A-%E2%80%8Aadvanced-guide/ for more info

sudo: false
cache: packages

# Use R language
language: r

#Define multiple R-versions, one from bioconductor
matrix:
  include:
  - r: devel
#   - r: devel
#     os: osx
#     osx_image: xcode10.1
  - r: release
    after_success:
  - r: release
    os: osx
    osx_image: xcode7.3
  - r: oldrel
  - r: 3.3
#  - r: 3.2 # Because of openxlsx requires R >= 3.3
#  - r: 3.1 # Because of openxlsx requires R >= 3.3
