# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# see https://www.r-bloggers.com/travis-ci-for-r%E2%80%8A-%E2%80%8Aadvanced-guide/ for more info

sudo: false
cache: packages

# Use R language
language: r

r_github_packages:
  - awalker89/openxlsx

#Define multiple R-versions, one from bioconductor
matrix:
  include:
  - r: release
    after_success:
  - r: devel
  - r: release
    os: osx
    osx_image: xcode7.3
#   - r: devel
#     os: osx
#     osx_image: xcode10.1
